"""dodan email

Revision ID: 34174e1b525a
Revises: f41fee5d9f27
Create Date: 2022-01-21 10:34:44.629068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34174e1b525a'
down_revision = 'f41fee5d9f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
